# Generated by Django 4.2.9 on 2024-02-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, choices=[('M3', 'discrete mathematics'), ('computer architecture and organisation', 'computer architecture and organisation'), ('operating system', 'operating system'), ('graphics and multimdeia', 'graphics and multimdeia'), ('computer networking', 'computer networking'), ('python', 'python')], max_length=45, null=True)),
                ('key', models.CharField(default='qzdDMfWDwwW9a1F1', editable=False, max_length=12, unique=True)),
            ],
        ),
    ]
