# Generated by Django 4.2.9 on 2024-02-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(default='AtpJICdTRflCtl3l', editable=False, max_length=12, unique=True),
        ),
    ]
