# Generated by Django 4.2.9 on 2024-02-09 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_record_session_alter_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(default='7uxawM2RDD7RWkpq', editable=False, max_length=12, unique=True),
        ),
    ]
