# Generated by Django 4.2.9 on 2024-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_record_timestamp_alter_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="key",
            field=models.CharField(
                default="c3y0fF5Wsfhdb2Gm", editable=False, max_length=12, unique=True
            ),
        ),
    ]
