# Generated by Django 4.2.9 on 2024-04-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
